src/main.rs
Hello!
Thanks for your feedback and tests @VictorMorenoJimenez we have added a new way to detect events into subfolder that improve the previous method. Now all events will be triggered.
Regards!
=> Added new way to detect events in subfolders and ignore them

.github/workflows/code-testing-workflow.yml, src/event.rs, src/event/hash.rs, src/event/mod.rs, src/main.rs
Hello,
We have added clippy report into our workflow automatic procedure.
We have also fixed all reports provided by clippy and mentioned at #24 
Fixed an error related with `InvalidData` at checksum calculation time.
This PR closes #24
=> Added clippy automatic test (static code analysis)

pkg/deb/repository/release/fim_0.2.1-1_amd64.deb, pkg/deb/repository/test/fim_0.2.1-1_amd64.deb, pkg/rpm/repository/release/fim-0.2.1-1.x86_64.rpm, pkg/rpm/repository/test/fim-0.2.1-1.x86_64.rpm
Hello!
This PR is related to #30 
We want to upload the release packages to the LFS repository.
=> Upload release packages

.github/workflows/coverall.yml
Hi!
We have added a testing coverage tool to maintain the coverage level on new development.
Yay!
=> Add coverage report to FIM

.github/workflows/deps-analysis.yml
Hello!
We want to include cargo audit scan to review security issues.
This PR closes #23 
Regards!
=> Add cargo audit

src/config.rs, src/main.rs
Hello team,
This PR closes #44 
We have included some fixes:
- Fixed default config load on target/release or target/debug folder
- Fixed log folder generation order
- Added config load from same directory `./config.yml` load
- Moved default config load to a function, added unit tests.
Regards
=> Fix config loading errors

.github/workflows/code-testing-workflow.yml, .github/workflows/coverall.yml, pkg/deb/builder.sh, pkg/deb/debian/changelog, pkg/deb/debian/rules, pkg/deb/repository/test/fim_0.3.0-1_amd64.deb, pkg/rpm/builder.sh, pkg/rpm/fim.spec, pkg/rpm/repository/test/fim-0.3.0-1.x86_64.rpm, src/config.rs, src/hash.rs, src/index.rs
Hello!
Closes #46 
We have included the following changes:
- Added 0.3.0 testing packages
- Improved unit test of `get_config_path` method
- Added new required dependencies to package build dependencies list
- Updated changelog
- Added `index_template.json` inside package installation
- Fix warning of insecure parameter inside `config.rs`
- Added function to read template from various locations
Regards.
=> Include `index_template.json` inside package and apply minor fixes

config/index_template.json, src/event.rs, src/index.rs, src/main.rs
Hello!
Closes #50 
We have include minor fixes to improve stability and performance over network:
- Improved `index_template.json` template to specify fields.
- Added 30 seconds timeout to event sending.
- Improved debug logging on event send.
- Added 120 seconds timeout to index creation.
- Changed `block_on` function call to async/await model in `main.rs`
- Moved index creation to working loop, now the index will be created on each new day.
- Adapt the unit tests to such changes.
Examples
Regards.
=> Fix network mode block

.github/workflows/pkg-build-workflow.yml
Hello!
We have fixed and error in the runner repositories.
=> Fix runner repository error

.github/workflows/pkg-build-workflow.yml, pkg/deb/debian/changelog, pkg/deb/debian/control, pkg/deb/docker/Dockerfile, pkg/deb/docker/entrypoint.sh, pkg/rpm/docker/Dockerfile, pkg/rpm/docker/entrypoint.sh
Hello!
We have included support to Ubuntu Xenial.
We added CentOS 7 package build test into our test suite.
Included Ubuntu Xenial package build test.
=> Include Ubuntu Xenial support and CentOS 7 package build test

.github/workflows/install-test.yml
Hello!
This PR closes #92 
We have included a new install workflow file to build and test installation of Windows MSI, Debian package file DEB and CentOS package file RPM.
=> Include Windows, Ubuntu and CentOS installation test

README.md
Hello!
This PR is related to #115. We want to include a better description of the project and links to explain details about it.
=> Improve README definition

src/utils.rs
Hello!
This PR closes #122 where nano is producing an error into FIM procedure. We have fixed and tested the error.
The rest of the AUID matter will be included in this issue https://github.com/Achiefs/fim/issues/134
=> Fix panic in specific nano usage scenario

pkg/deb/builder.sh, pkg/fim.1, pkg/msi/builder.ps1, pkg/msi/fim.wxs, pkg/rpm/builder.sh
Hello!
We have included automatic package versioning on RPM, DEB and MSI packages to avoid human error at bumping phase.
This PR closes #135
=> Added Automate version replace on packages

src/monitor.rs
Hello!
We have added a new way to control Audit rule, with this manner we can include read events inside a folder.
This PR closes #134
=> Add rule parameter to control Audit rule

src/auditevent.rs, src/config.rs, src/event.rs, src/main.rs, src/monitor.rs, src/utils.rs, test/unit/config/linux/audit_rule.yml
Hello!
This PR closes #141 
Github informed of some code issues that is recommended to fix.
We have fixed each one and in addition we detected and fix a problem with Audit rule removal when it is customized.
=> Fix code scan reported issues

src/monitor.rs, src/utils.rs
Hello!
This PR is related tho #141.
We have added a simple solution to solve the warning in code scanning.
=> Solve the complex match warning

src/appconfig.rs, src/logreader.rs
Hello!
This PR closes #165 
We have changed the way to resolve unwraps and clone in some scenarios.
=> Fix codescan issues

Cargo.toml, src/appconfig.rs, src/rotator.rs
Hello,
We have added minor fixes related to scanned issues.
This PR closes #172
=> Fix code scanning issues

.github/workflows/install-test.yml, .github/workflows/system-tests-workflow.yml
Hello!
This PR closes #183 
We have added manual steps to perform the same tests on CentOS 7, soon we will need to update to another distro.
=> Fix CentOS 7 workflow

Cargo.toml, pkg/deb/debian/changelog, pkg/rpm/fim.spec, src/appconfig.rs, src/init.rs
Hello!
This PR closes #187
We have researched about simplelog configuration to include this modification.
Bumped to 0.5.3
=> Add date to log line
